image:
  file: .gitpod.Dockerfile
tasks:
  - command: gp await-port 8000 && sleep 3 && gp preview $(gp url 8000)
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
ports:
  - port: 8000
    onOpen: open-preview